require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'app/views/**/*'
    - 'config.ru'
    - 'config/environments/*'
    - 'spec/**/*'

Layout/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
