default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: te/dev_grocery
  host: localhost

test:
  <<: *default
  database: te/test_grocery
  host: localhost
